### ISSUE TITLE
Where to find the generated Fixes ?

### ISSUE THREAD

**Issue by cheikh-sadbouh** [dvmarcilio/SpongeBugs#35]
i am trying to use  spongeBugs  and did some  example but it seems like from the console it does detect the bug but can not figure out where the generated fix are stored. Kindly guide  me to understand its usage.

<img width="886" alt="emptiness" src="https://user-images.githubusercontent.com/23532672/139665504-e500cf2a-bbfc-468b-b7c5-27731ba6e267.PNG">

**Comment by dvmarcilio** [comment]
SpongeBugs directly modify the files. One way to check the modifications is through `git diff` if you are working with a large project. In this case, SpongeBugs modifies the file, and your editor/IDE should notice the modification. 

If it doesn't work, can you please share how you are running it? Are you passing the java file path or a directory as an argument?

**Comment by cheikh-sadbouh** [comment]
Thank you for your reply, I am passing the java file name as an argument, but it does not  modify  the file  ,you can see the below image.


<img width="922" alt="emptiness1" src="https://user-images.githubusercontent.com/23532672/139671741-32c26b88-3454-44de-a9a2-df81efc134e9.PNG">

**Comment by dvmarcilio** [comment]
I'm afraid that relative paths do not work. Could you try passing the file's full path?

**Comment by cheikh-sadbouh** [comment]
I got an exception when passing the full path.

<img width="569" alt="exc" src="https://user-images.githubusercontent.com/23532672/139673006-fd89e68a-5c6c-4cf6-bac8-b48ce902e43f.PNG">

**Comment by dvmarcilio** [comment]
I guess the exception happens because you have a space on your file path. Can you try surrounding it with `"`?

**Comment by cheikh-sadbouh** [comment]
see the below image the path was accepted with no error but file has not been changed

<img width="627" alt="nothingchanged" src="https://user-images.githubusercontent.com/23532672/139674280-9c6477b7-9a7b-405a-af41-a40072ae23b2.PNG">

**Comment by dvmarcilio** [comment]
I'm unsure about that path.  Unfortunately, the outputs are not helpful, sorry about that.

Does it work if you run `java -jar spongebugs-runner-20-12-19.jar "C:/Users/Cheikh Saadbouh/Documents/abobakr/spongebugs/src/com/panda/fn/TestForCollectionEmptiness.java"`? It works here with a similar file with a path with space.

**Comment by cheikh-sadbouh** [comment]
it works Thank you for helping.
